[package]
name = "virtual_viewer_new"
version = "0.1.1"
edition = "2021"

[dependencies]
led_matrix_zmq = { path = "../" }

gfx = "0.18.3"
ggez = "0.9.3"
glam = { version = "0.24.2", features = ["mint"] }
structopt = "0.3"
